TILE_EMPTY = -1;
TILE_MOUNTAIN = -2;
TILE_FOG = -3;
TILE_FOG_OBSTACLE = -4;

window.TILE_EMPTY = TILE_EMPTY;
window.TILE_MOUNTAIN = TILE_MOUNTAIN;
window.TILE_FOG = TILE_FOG;
window.TILE_FOG_OBSTACLE = TILE_FOG_OBSTACLE;
